### ISSUE TITLE
Add From IMDB's Popular Shows Broken

### ISSUE THREAD

**Issue by maticks81** [linuxserver/docker-medusa#21]
When using Add From IMDB's Popular Shows the system breaks.

Error message is as below, when the library is empty it seems to work which is strange.

Fetching of Recommender Data failed. Exception:
No module named _bsddb

Can't find any errors in the logs anywhere to provide more information.

**Comment by thelamer** [comment]
Can you purge the files in `/config/cache` and restart the container ? It looks like you are experiencing the exact same issue as here: 

https://www.bountysource.com/issues/62625294-no-module-named-_bsddb

**Comment by CHBMB** [comment]
Closing due to no response from OP and no other reports
