### ISSUE TITLE
Upgrade Python version to >= 3.5

### ISSUE THREAD

**Issue by medariox** [linuxserver/docker-medusa#25]
Hello all! Medusa dev here ✋ 

We have noticed that your Docker image is popular! 🎉 
I'm here to inform you that we are fully Python 3 compatible since a few releases.

As you may already know Python 2.7 will reach its EOL on 01.01.2020. This means it won't be receiving any official support nor security patches anymore. For this reason we will end support for any Medusa installs using Python 2.7 on the same date.

We kindly ask you to update the Python version to >= 3.5 (preferably 3.6 or 3.7) as soon as possible. The update won't require any intervention from the end users.

Thank you for your continued support 👏

**Comment by CHBMB** [comment]
@medariox Thanks, will sort it out.

**Comment by aptalca** [comment]
@medariox can we get some help from your team/users in testing the new python3 based image? This is very slimmed down compared to the old py2 baseimage. We want to make sure that it doesn't break any functionality or maybe plugins.

They would just have to switch `linuxserver/medusa` with `lspipepr/medusa:v0.3.5-pkg-5bdd7f36-pr-26` to get the new image.

Thanks

**Comment by medariox** [comment]
@aptalca 
Thank you. I've tried out the image and it seems to work great. The only thing I would recommend is setting the locale to UTF-8.  This is important for Python to be able to use the correct encoding.
A way to do that would be to set the LANG environment variable, e.g.:
`ENV LANG='en_US.UTF-8'`
There are surely also a few other ways to do it.

**Comment by aptalca** [comment]
Yeah, good point. That was handled in the old baseimage but seems I missed it during transfer. Thanks
