### ISSUE TITLE
Manual or auto Post Process with existing symlink using keeplink funtion

### ISSUE THREAD

**Issue by 60wsr** [linuxserver/docker-medusa#35]
Traceback (most recent call last):
  File "/app/**********/**********/post_processor.py", line 519, in keeplink
    helpers.symlink(cur_file_path, new_file_path)
  File "/app/**********/**********/helpers/__init__.py", line 391, in symlink
    if os.path.exists(dst):
FileExistsError: [Errno 17] File exists:

It think it should delete/unlink and then recreate. Now it is crashing

Current setup:
/tv_shows - symlinks for Medusa with all the tv_shows
/torrent/new_downloads - pre Post-Process location
/torrent/finished_downloads - permanent seeding location

Also most of the symlinks have errored out as when setting up the 'Post-Processed seeding torrents location" first the Post-Processing is creating a reverse symlink to /torrent/new_downloads and then calling the above mentioned procedure with path /torrent/finished_downloads for permanent storage , but the symlink is still linked to /torrent/new_downloads  so it is unusable.

**Comment by thelamer** [comment]
You can't symlink across mounts like this the host will not have any idea what to do with them. As it stands the container is configured to have different directories for TV shows and downloads. You would need to do some modifications in a fork to have links or file moves work. 
As far as Docker understands these are different underlying filesystems inside the container.
