### ISSUE TITLE
Update PMS library not working

### ISSUE THREAD

**Issue by 60wsr** [linuxserver/docker-medusa#36]
Hi,

All boxes from Notifications -> Plex Media server are completed with the correct information (token, user, password, server ip:port) and I`m receiving the blue box with (error trying to update plex).
What is surprisingly, when using the Test Plex Media Server, the test is ok even if the Token field is empty.

Error received: 
Thread_2 :: [] PLEX: Unauthorized. Please set TOKEN or USERNAME and PASSWORD in Plex settings

**Comment by Roxedus** [comment]
Looks like you already filled this issue correctly upstream.
