### ISSUE TITLE
Container does not contain correct version

### ISSUE THREAD

**Issue by dsm1212** [linuxserver/docker-medusa#39]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

In the general info box i get:

Medusa Info: | 
Branch: master
Commit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
Version: 0.5.25

But that commit number is old and is not the 0.5.25 commit. The 0.5.25 commit is 5de42f0b40aefdecd3613b045391c691c3cedf87.

It's been stuck like this for a while, looking at the docker file it seems to be using the wrong path to the release tarball. Maybe they changed that path. It must have an old medusa.tar.gz file in /tmp it is using when it tries to do the build. So, the correct path should be like https://github.com/pymedusa/Medusa/archive/refs/tags/v0.5.25.tar.gz. The folders refs and tags are not in the docker file. I suggest you also rm the download file after unpacking it so this doesn't go unnoticed again.

**Comment by dsm1212** [comment]
I see it does remove the temp files, but I guess if the download fails then the unpacked code from the last run is left in place. Probably the download error just needs to be caught.

**Comment by aptalca** [comment]
I don't follow.

There is no such thing as files left over from the last run. Each docker image is a fresh new build with one version as tagged.

If your container is based on the latest image, you are running the latest version we built and tagged. I don't know where medusa is getting that commit hash from but it's unlikely that it's from the build you're actually running as there is no git head.

**Comment by aptalca** [comment]
I just fired up a fresh instance and it shows `unknown` for both branch and commit, as expected. But it does show the correct version.

So whatever commit you're seeing is not accurate and likely outdated info.

**Comment by dsm1212** [comment]
Hmm, so you are saying maybe I have the latest bits but the container reports the wrong commit number? I deleted the image and downloaded at least five times over the past few months. How is this possible?

**Comment by dsm1212** [comment]
Wait, how is unknown as expected? Medusa has always shown me when there are more commits. It can’t do that if the commit used is unknown.

**Comment by thespad** [comment]
It's just reading a string out of the config.ini. It can't update it without the git binary but I don't think it even tries when it's running in docker because it has no need to.

![image](https://user-images.githubusercontent.com/8425502/158063077-af3ffffe-e38b-48c7-8ec4-7122ae4bab7d.png)

![image](https://user-images.githubusercontent.com/8425502/158063105-14745dd0-6592-4714-819e-8f25561bd61c.png)

**Comment by dsm1212** [comment]
Ok, I think maybe I or someone here tried an update of the container somehow. That got a value written into my config.ini and it's stuck there since I'm never actually updating. Thanks, closing.
