### ISSUE TITLE
Please add support for env variables GIT_BRANCH and GIT_COMMIT

### ISSUE THREAD

**Issue by p0psicles** [linuxserver/docker-medusa#40]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hi guys. I'm the maintainer of the project https://github.com/pymedusa/Medusa. You have setup a linuxserver image in https://docs.linuxserver.io/images/docker-medusa, which are very grateful for. As lot's of our users are using that image.

But in the last couple of years we've also started pushing our own image to docker hub. And lately we've added some integrations. One of these is that we've made Medusa aware if it's running in docker yes or no. We've done this by adding two ENV variables from the docker build script. `GIT_BRANCH` and `GIT_COMMIT`.  These env variables are also used to display the current running commit and branch from the Medusa ui.

It's important that medusa knows it's running in docker, so we can disable some of the git update code.

Would it be possible that you mimic that behavior? This is our current Dockerfile: https://github.com/pymedusa/Medusa/blob/develop/Dockerfile for reference.

I also noticed this issue which is somewhat related: #39

**Comment by p0psicles** [comment]
I just noticed that you guys of course have to get the tar.gz files from our repo. So you might nog get a commit. And the branch value is probably fixed to `master`. If you don't have a commit, I can have medusa only check for the `GIT_BRANCH` env variable.

**Comment by Roxedus** [comment]
The release tag is available to us, so if you can be set up to read that, that would be best

**Comment by p0psicles** [comment]
So to be clear. The env variable `MEDUSA_RELEASE` should be available in the image?
Is that already the case, or do you need to make a change for that?

When i log in to the image, I see the following env variables.
```
HOSTNAME=2f5fb46ceb83
SHLVL=1
HOME=/root
PS1=$(whoami)@$(hostname):$(pwd)\$ 
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
PWD=/
TZ=Europe/London
affinity:container==30f64946e11aeb97ffa106df29c53b700b3a382eee7c95d83b9f656a527e8ed9
```

**Comment by thespad** [comment]
With the release builds presumably the GIT_COMMIT is the commit associated with that release? And is it the full commit sha or just the first 8 characters?

**Comment by p0psicles** [comment]
Yes it's the commit associated with the release. We currently use the full commit. But short would also be fine.

**Comment by p0psicles** [comment]
With the advice from @reconman i'm going with the route to check for a `/.dockerenv` file. Which seems to work pretty well.
You could still add support for the GIT_BRANCH and GIT_COMMIT env vars. But because your only building the master branch, it's not that of a high prio.
