### ISSUE TITLE
Please add ffpmeg pkg, to provide ffprobe

### ISSUE THREAD

**Issue by beavis69** [linuxserver/docker-medusa#42]
Hello,

Can you please add ffmpeg pkg to the docker files so that medusa can use ffprobe for pos-tprossesing files.

see https://github.com/pymedusa/Medusa/releases/tag/v1.0.7

Thank you.

**Comment by aptalca** [comment]
You can install it via this mod: https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by beavis69** [comment]
I modified my docker-compose file to add :
```
    environment:
      - DOCKER_HOST=medusa
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=ffmpeg
```
ffmpeg was installed after restarting container

Thank you.
